### PR TITLE
Minor editing.

### PR DESCRIPTION
**Pull request by griznog**
Some minor edits and adding context in some places.

### CODE REVIEW

**Comment by vsoch** [comment]
Let me know when you are finished adding quotes and I'll finish up with the formatting issues.

**Comment by vsoch** [comment]
@griznog we totally dropped the ball here! Are you sure you don't want to merge the work you did?

**Comment by griznog** [comment]
I didn't realize I had a PR still open from that fork, was just cleaning up my far too long repository list. I should revisit this at some point, but free time is a scarce commodity.

**Comment by vsoch** [comment]
Gotcha, well it’s nice to say hello! Hope you are ok during these craptastic pandemic times 😆

**Comment by griznog** [comment]
Things are going pretty well, as far as I know. But they don't tell me much :) Hope you are staying out of trouble, or getting into interesting trouble.

**Pull request closed without merging**
