### PR TITLE
Added wisdom griznog shared with SCGPM

### PR DESCRIPTION
**Pull request by pbilling**
Wisdom from the SCGPM slack!

### CODE REVIEW

**Comment by vsoch** [comment]
hey @pbilling this is fantastic! 

Don't worry about the failing test for the formatting - I'll pull your branch now and run the linter for you. I might also add a test to ensure that the wisdom entries are all formatted correctly. Give me a few minutes!

**Comment by pbilling** [comment]
Hey @vsoch, this is great!! Thanks for putting it all together!

And sorry about the formatting issue - do whatever you need to do; no rush!

**Comment by vsoch** [comment]
All set @pbilling ! I opted to open a second PR to test cleanly instead of pushing to your branch, in case there was any weirdness with GitHub actions and adding the new tests. Specifically if you look here: https://github.com/vsoch/griznog/pull/2

 - I did the linting with black
 - I added a test to ensure that each quote has both "date" and "quote" and is a string.
 - I added a note to the changelog to reference the PR #1 
 - and of course bumped the version!

The release on pypi https://pypi.org/project/griznog/0.0.11/ and the containers are also already built! https://quay.io/repository/vanessa/griznog?tab=tags Thanks for your contribution!

**Comment by pbilling** [comment]
So cool! Thanks @vsoch

**Pull request merged**
